### ISSUE TITLE
Feat: [Car] 도로 내 차량 검출 기능 구현

### ISSUE THREAD

**Issue by ParkYoungMoon** [66yurimi99/DriverMonitoring_AutoDriving#16]
## Description  
주행 영상 내 자동차 감지 기능 
* Input: 주행 동영상 ( .mp4)
* Output: 도로 내 자동차 감지 영상( .mp4)

## Todo  
* 기능 1 : CPU,GPU 사양에 맞는 객체 탐지 모델 YOLO 버전 선정
* 기능 2 : GPU 가속화를 통한 연산 속도 향상
* 기능 3 : 선정 모델을 이용한 차량 검출

## 목표
목표 예시
![차량 감지](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/148414302/d4162cd3-f2c8-41d8-b61d-3e25915a13f1)
참고한 자료, 링크를 추가하세요.

## 결론
- [x] YOLO 버전 
- [x] GPU 
- [x] 차량 검출

## 모듈화
- [x] 차량 검출

**Comment by YuNayeong** [comment]
[yolo 버전별 처리 속도 비교-FPS]

#yolov4-tiny
![yolov4tiny_fps](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/147594641/b9f2c205-68f3-4844-adcc-e11671140963)

#yolov7
![yolov7_fps](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/147594641/32fec051-3ddd-4635-9c57-2f20f28adf38)

**Comment by YuNayeong** [comment]
## 결론
**1. YOLO 버전 : YOLO V4_tiny**
  버전별 영상 처리 속도 비교를 위해 fps 값으로 비교 후 가장 높은 yolo v4_tiny 모델 사용
**2. GPU**
  +업데이트
**3. 차량검출**
  yolo모델을 사용해 검출된 차량에 대해 최적의 라운딩 박스를 그리고 car, 인식율 표시

## 모듈화
 +지금까지한 구현한 부분에 대해 모듈화 진행 필요

**Comment by ParkYoungMoon** [comment]
- 테스트 케이스
  > CASE 1. GPU, CPU 비교
  > CASE 2. Yolo 모델 비교
  > CASE 3. 차량 검출
  > CASE 4. 차량 간의 거리에 따른 충돌 안전 여부 판단
