### ISSUE TITLE
Feat: [Driver, Car] 파트 간 데이터 통신

### ISSUE THREAD

**Issue by jis0202** [66yurimi99/DriverMonitoring_AutoDriving#25]
## Description  
Driver와 Car 파트 간 운전자 상태 정보(`flag`) 통신
* 운전자 상태 정보
    - 데이터베이스와 연동
    - `flag = 0` : 운전 가능한 상태
    - `flag = 1` : 정상적으로 운전할 수 없는 상태 (ex. 졸음 등)
* 통신 방법
    - 웹 서버를 통한 DB flag 값 접근
    - HTTP / GET
<br>

## Todo  
- [x] Driver, Server 간 HTTP 통신
- [x] Car, Server 간 HTTP 통신
<br>

**Comment by jis0202** [comment]
windows내장 라이브러리 wininet을 이용한 http 통신 예제입니다. 

#include <iostream>
#include <windows.h>
#include <wininet.h>
#include <string>

int main() {
    HINTERNET hInternet, hConnect;
    DWORD bytesRead;
    char buffer[4096];

    std::wstring a(L"http://54.175.8.12/flag.php");
    //std::wstring b(L"?sleep=1");

    // 초기화
    hInternet = InternetOpen(L"HTTP Example", INTERNET_OPEN_TYPE_DIRECT, NULL, NULL, 0);
    if (!hInternet) {
        std::cerr << "InternetOpen failed." << std::endl;
        return 1;
    }

    // HTTP GET 요청
    hConnect = InternetOpenUrl(hInternet, (a + b).c_str(), NULL, 0, INTERNET_FLAG_RELOAD, 0);
    if (!hConnect) {
        std::cerr << "InternetOpenUrl failed." << std::endl;
        InternetCloseHandle(hInternet);
        return 1;
    }

    // 응답 읽기
    while (InternetReadFile(hConnect, buffer, sizeof(buffer), &bytesRead) && bytesRead > 0) {
        std::cout.write(buffer, bytesRead);
    }

    // 정리
    InternetCloseHandle(hConnect);
    InternetCloseHandle(hInternet);

    return 0;
}

**Comment by 66yurimi99** [comment]
통신용 서버 구축 완료했습니다.
#27 이슈의 "HTTP 통신 예시" 참고해서 작업해주세요!

**Comment by jis0202** [comment]
while 내부(2 ~ 6)에 server flag를 이용한 if문 필요

```cpp
int main(int argc, char* argv[])
{
	VideoCapture video("Line.mp4");	// INPUT : 도로주행 동영상
	if (!video.isOpened())	return -1;			// ERROR : 동영상 파일 열기 실패

	Mat img_frame;
	video.read(img_frame);

	width = img_frame.cols;
	height = img_frame.rows;

	Point2f srcPts[4] = { };
	Point2f dstPts[4] = {
		Point2f(0,0),
		Point2f(img_frame.cols * 0.3, 0),
		Point2f(img_frame.cols * 0.3, img_frame.rows * 0.3),
		Point2f(0, img_frame.rows * 0.3)
	};

	// 1. Set RoI (첫번째 frame에서 마우스 클릭으로 ROI 영역 지정)
	SetROI(img_frame, srcPts);

	// RoI 영역 지정이 완료된 후, 차선 검출 프로그램 시작
	namedWindow(window_capture_name4);
	while (video.read(img_frame))
	{
		// 2. Perspective Transform (3D -> 2D : top view)

		// 3. Image Preprocessing (Convert "RGB Color" Image to "HSV-Value + HSV-Yellow")

		// 4. Get Lanes

		// 5. Perspective Transform (2D -> 3D)

		// 6. 방향 구하기
		// 좌 / 직진 / 우

		// 7. Put Text

		Mat img_result;
		bool flag = true;
		PutText(img_result, flag, 0.0);
#if 0
		bool flag = true;
		if (flag)
		{
			putText(img_result, "Auto", Point(20, 60), 1, 4, Scalar(0, 255, 255), 5);
		}
#endif
		imshow(window_capture_name4, img_result);
		waitKey(1);
	}

	return 0;
}
```
