### ISSUE TITLE
Cleanup: [Driver] 운전자 인식 주석 및 모듈화

### ISSUE THREAD

**Issue by akaError404** [66yurimi99/DriverMonitoring_AutoDriving#4]
## Description  
운전자 눈 인식 ver1.0  모듈화 및 주석
<br>

## Todo  
- [x] 독립 코드 모듈화
- [x] 1차 프로토타입 코드 주석 
<br>

## Etc
![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/86766617/22dbb774-7c5e-4968-8415-fc1cdabfb741)

**Comment by daron135** [comment]
눈이 아름다워요

**Comment by akaError404** [comment]
> 눈이 아름다워요

감사합니다.
