### ISSUE TITLE
Refact: [Car] 차선 검출 기능 - 통합 및 모듈화

### ISSUE THREAD

**Issue by 66yurimi99** [66yurimi99/DriverMonitoring_AutoDriving#6]
## Description  
각자 구현한 검출 알고리즘의 성능을 비교한 후, 가장 효과적인 방식으로 통합 및 모듈화
<br>

## 비교 Sequence
다음과 같은 내용을 포함해 댓글로 비교 결과를 올려 주세요.
- 테스트케이스
  > CASE 1. 일반 아스팔트 - 어두운 색상 도로
  > CASE 2. 비포장 - 밝은 색상 도로
  > CASE 3. 그림자 생기는 부분

- 결과 비교 스크린샷 12장 ( 테스트케이스 3개 X 알고리즘 4개 )

- 결론 ( 채택된 알고리즘 및 소스코드 )

<br>

## 비교 완료
- [x] 기능 1 : RoI 영역을 마우스로 지정 (23.10.19 완료)
- [x] 기능 2 : 시점 변환 (23.10.24 완료)
- [x] 기능 3 : 이미지 전처리 - 유림 테스트 (23.10.26 완료)
- [x] 기능 4 : 차선 검출 - 영식 테스트 (23.10.28 완료)

<br>

## 모듈화
- [x] 기능 1 : RoI 영역을 마우스로 지정 
- [x] 기능 2 : 시점 변환 
- [x] 기능 3 : 이미지 전처리 
- [x] 기능 4 : 차선 검출

**Comment by daron135** [comment]
* 테스트케이스

> CASE 1. 일반 아스팔트 - 어두운 색상 도로
![testcase1](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/e1d015d0-7eb1-42af-8416-548e17bdda88)
> CASE 2. 비포장 - 밝은 색상 도로
![testcase2](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/c24a0eb6-06ab-4a7a-9ef3-90aac642c306)
> CASE 3. 그림자 생기는 부분
![testcase3](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/43f4516d-eaf9-481b-bfc9-e09103bb973d)

* 위의 이미지 3개 가지고 각각의 알고리즘으로 구현된 코드 실행 및 비교할 예정

**Comment by 66yurimi99** [comment]
넹 위 이미지 3장을 Input으로 테스트 진행하겠습니다!

**Comment by daron135** [comment]
### 2. **결과 비교**

> CASE 1. 일반 아스팔트 - 어두운 색상 도로

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/780dfefd-6b99-404f-aeb2-23a26b886276)
* LaneDetection_youngsik

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/11a8a016-7756-44de-b5a0-0b4531647084)
* LaneDetection_nayeong

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/ae79e55e-aa0f-4e1e-ae43-bb0c5c2d2a4e)
* LaneDetection_youngmoon

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/528cf464-760f-47ad-a024-8e83852d017e)

* LaneDetection_yurim

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/23a99e70-6583-42e6-966b-232bbbc3934f)

***
> CASE 2. 비포장 - 밝은 색상 도로

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/b400a49f-305c-47d8-8070-4f30d40449b7)

* LaneDetection_youngsik

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/24032477-5ed7-4ac0-9613-fecd544cb14e)
* LaneDetection_nayeong

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/12ca60b8-700a-4a75-a4c5-9a38f5cb3143)
* LaneDetection_youngmoon

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/494ec9ff-e0af-4481-9d45-49b7b29b48dc)
* LaneDetection_yurim

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/0dda279a-cc1a-40d2-bb51-635ec2650e53)
***
> CASE 3. 그림자 생기는 부분

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/6f03f6c8-3988-4593-8787-19ad4a94bb99)

* LaneDetection_youngsik

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/2c138366-212b-43e4-b98a-bdfba3682ee2)
* LaneDetection_nayeong

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/932089e9-ad7e-4f0c-a369-d62e03a10ede)
* LaneDetection_youngmoon

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/c109b579-9d52-4ef1-b30b-64fc81a036b7)
* LaneDetection_yurim

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/140676907/e92c579c-955e-4a3a-90ba-5f3a13c31a3b)
### 3 **결론**
000의 알고리즘 채택

**Comment by 66yurimi99** [comment]
## 결과 비교 - 이미지 전처리

> CASE 1. 일반 아스팔트 - 어두운 색상 도로

1) 이진화 적용 전/후
![Case1 - 1_이진화 적용 전](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/e976653c-2428-408f-bda2-948c01f5096f)
![Case1 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/6b9530f9-23c8-46d6-b618-9bd8043caf20)

2) 노이즈 제거 전/후
![Case1 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/5c31b939-199f-4c90-bd3e-fb3a7fbb9d51)
![Case1 - 2_노이즈 제거](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/85988c43-595a-4fde-85be-9f1f80080c1c)


3) 밝기 조절 전/후
![Case1 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/89aeb9bb-d997-476a-a590-27175ec221e3)
![Case1 - 1_이진화 적용 후+밝기조절](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/c42d3e95-3a63-4b93-b383-0366f2938661)



***
> CASE 2. 비포장 - 밝은 색상 도로

1) 이진화 적용 전/후
![Case2 - 1_이진화 적용 전](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/2ffd707d-2ff0-459f-9f82-05db6e6b2b33)
![Case2 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/5f4270e5-630e-4be9-aa7e-080522ecaa74)

2) 노이즈 제거 전/후
![Case2 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/de503ef5-25dd-4c4a-9382-e37dfc5ecc41)
![Case2 - 2_노이즈 제거](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/7c979d5a-b571-441b-b252-d1d199705d2f)


3) 밝기 조절 전/후
![Case2 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/b22d7a60-641b-4c76-ba1b-2afbcd84889b)
![Case2 - 1_이진화 적용 후+밝기조절](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/8d5fd76a-6585-48e8-9968-aa28287a3ba4)



***
> CASE 3. 그림자 생기는 부분

1) 이진화 적용 전/후
![Case3 - 1_이진화 적용 전](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/30c9fb09-7fe2-44dc-b669-89f6f90835c7)
![Case3 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/88f898ab-7528-4d3f-939c-8804dfbe298b)

2) 노이즈 제거 전/후
![Case3 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/08fb31de-a90f-4fb9-bbd6-6b1807215c9a)
![Case3 - 2_노이즈 제거](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/e9cea37d-9c27-45a2-8245-58f8db601779)

3) 밝기 조절 전/후
![Case3 - 1_이진화 적용 후](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/6b42d8f3-c223-4f97-9fd8-12040ddd7e38)
![Case3 - 1_이진화 적용 후+밝기조절](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/90135804/9285af9c-c6a5-4e4b-96ee-3f6356150361)



***

## 결론 - 이미지 전처리
### 1. 색상 변경 알고리즘 : Yellow + LAB White 
색상 변경 알고리즘은 다양한 케이스에서 일관성 있는 성능을 보이는 두번째 알고리즘을 채택한다.  (based on `LaneDetection_nayeong`)

### 2. 노이즈 제거 : Opening 연산 1회 적용
CASE 2와 같이 주행 중 노이즈가 검출되는 영역이 있어, 노이즈 제거가 필요하다고 판단된다.  
차선 외에 검출된 노이즈 제거를 위해 Opening 연산을 1회 적용한다.  (based on `LaneDetection_yurim`)

### 3. 기타 : 적용하지 않음
채택된 색상 변경 알고리즘 이미지에서 기타 전처리 연산(밝기 조절(Darkenling) 및 Blurring 연산 등)은 성능에 영향을 거의 미치지 않기 때문에 처리 속도 향상을 위해 생략한다.
