### ISSUE TITLE
Refact: [Driver] 운전자 인식 영상 전처리

### ISSUE THREAD

**Issue by jis0202** [66yurimi99/DriverMonitoring_AutoDriving#8]
## Description  
-조명에 따른 운전자 인식률 개선을 위해 원본 영상 전처리 과정
<br>

## Todo  
- [ ] 원본 영상 전처리
- [ ] 

<br>

## Etc
기타 사항 또는 참고가 될 예시 자료, 링크를 추가하세요.

**Comment by jis0202** [comment]
히스토그램 평활화
색상 보정(HSV, RGB..)

**Comment by jis0202** [comment]
convet to grayscale ->
histogrameq ->
detecface ->
convert to RGB

두 이미지에서 가시적인 얼굴 인식성능 개선점 찾을 수 없음

![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/141535958/02b468cc-48e6-4696-a754-d4588b2f5cba)
![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/141535958/7dcb5c77-b4a7-42db-a649-a611322b48b4)

**Comment by akaError404** [comment]
Improve the Image using log transformation, gamma transformation

**Comment by akaError404** [comment]
![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/86766617/8243e43d-0772-48ad-9552-e1e3034c66cf)
Left image is origin image and right image is image which is applied gamma transformation(r= 1.5)
But, the accuracy is same.

**Comment by akaError404** [comment]
![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/86766617/f1af718e-e5bc-4a6d-b76a-dd72157cfb13)
11 o'clock direction is original img, 2 o'clock direction is log transformation image(i am trying to fix it), 6 o'clock direction is gamma transformation(r= 2.0).

**Comment by akaError404** [comment]
![image](https://github.com/66yurimi99/DriverMonitoring_AutoDriving/assets/86766617/869e27b7-68a0-49e1-9a53-479680484725)
original image - gamma transformation(r=2.0) - log transformation
When i see that picture, gamma TF has a best performance (but tiny difference).
But when the outside is dark, all of them can't find my eyes exactly.
